### ISSUE TITLE
Black bars for PNGs

### ISSUE THREAD

**Issue by arihsieh** [hafaio/repub#10] opened 2024-10-10 19:06 UTC
Hi there! I am so so grateful for this tool, its amazing! 
I have run into an issue though, i dont know if it happens in the rm2, but i just bought the rmpp, and it exports the pngs weirdly, sometimes there are like giant black bars and sometimes it just doesnt appear at all, this is an example:
https://medium.com/@marcodelpra/generative-adversarial-networks-dba10e1b4424
<img width="1454" alt="image" src="https://github.com/user-attachments/assets/fd6b5b9d-c250-460f-9ff7-fef6a05a82e2">
Is it possible to fix? Its kinda weird because I havent read about it in reddit or anywhere else.
Again, thank you for this tool, its so so so much better than the native one <3

**Comment by erikbrinkman** [comment] 2024-10-11 02:55
Thanks for reporting this! I confirmed that I also see this behavior. I don't think it's just pngs, but probably something with the way medium is rendering images of equations, as AFIAK I've seen pngs work fine.

I'll try to see if I can find what's causing this, but I'm pretty busy lately, so if you have time, you can download the webpage using "save page as" -> "web page; single file" and then pass that file into `bun cli -v <file.mhtml>` to see if you can figure anything else about how it's getting parsed. Otherwise I'll update here when I've found something.

**Comment by erikbrinkman** [comment] 2024-10-11 03:59
Looking at this a little bit, the problem seems to be the way that webp images are handled. They should be converted to pngs, but unfortunately this is something done exclusively in chrome, not even in headless js enviornments, so I need to dig a little deeper.

**Comment by arihsieh** [comment] 2024-10-11 23:32
Thank you for looking into this! I really appreciate it

**Comment by erikbrinkman** [comment] 2024-10-12 19:47
Okay, so the problem wasn't related to format at all. The images in question were largely transparent. However, I was converting webp images to jpg images, which don't have transparency. The transparent color was set to `rgba(0, 0, 0, 0)` so when the transparency was removed, the background was black, rather than the remarkable default of "white". Instead of trying to handle this, I just changed export to convert webp images to pngs where the transparency can be preserved, and voila, no more black equations.

This is currently pending publication as repub `v4.1.0`. Try waiting a day or so, and make sure your extension is up to this version. I'm going to close this assuming that this worked, but if you update and still the issue, please re-open!

**Closed as completed by erikbrinkman** 2024-10-12 19:47 UTC

**Comment by arihsieh** [comment] 2024-10-13 02:46
Its working perfectly now, thank you so so much!
