### ISSUE TITLE
Error on each use

### ISSUE THREAD

**Issue by jfowlie** [hafaio/repub#9] opened 2024-09-17 20:09 UTC
![image](https://github.com/user-attachments/assets/f536900e-7db2-447e-acae-1c4c4b186869)

I've got the plugin all configured and connected to my account. However, no matter what page I am on, when I click the rM button, it says 50%... 75%... and then err.

I am unable to find a place where the error is detailed.

**Comment by erikbrinkman** [comment] 2024-09-18 01:03
Thanks for reporting this! There are a few places you can find a more detailed error, by digging into the extension logs from the extension menu. **However**, I already know what the cause is. reMarkable updated their cloud API which broke this extension. Unfortunately the API isn't public, and the people whom I know figured it out before have moved on. I'm going to try and figure it out and will update this when I have.

In the meantime you have two options:
1. continue to use this by just downloading the epubs and uploading them using the app. Kind of a pain, but you should still get the images.
2. switch back to the normal extension without images until I get this fixed.

Sorry for the inconvenience!

**Comment by brianblank** [comment] 2024-09-18 01:07
I'm having the same problem.  Thanks for the suggested work arounds... going to try #1 for now.  And thanks again for the effort that you put into this extension.. this is way better than the official version.

**Comment by erikbrinkman** [comment] 2024-09-22 15:57
Okay, I have a work around that's not ideal, but works for now. As of v4.0.0 in the store, which should release shortly, you should be able to upload again. Unfortunately, the newer API doesn't allow modifying things like the font or the margin. It's not ideal, but this is what I have for now.

Since the extensions is more or less working, I'm going to close this. However, I'm going to be on the search for better apis to bring back some of the old functionality.

**Closed as completed by erikbrinkman** 2024-09-22 15:57 UTC
